// Seed notes — used on first visit when localStorage is empty.
// Each note has a numeric `created` + `updated` timestamp; display is relative.

const HOUR = 3_600_000;
const DAY = 86_400_000;
const NOW = Date.now();

const SOURCES = [
  {
    id: 'n-rates',
    pinned: true,
    tags: ['writing', 'essay/rates'],
    body: [
      '# on rates, and the quiet form of trust',
      '',
      'i used to think pricing was a spreadsheet problem. it is not. it is a trust problem wearing a number.',
      '',
      'the price you quote is a sentence about how much of your year you are willing to spend on someone else\'s problem. anyone who argues it is arguing with the sentence, not the math. a discount, carelessly given, is a retraction of the sentence — and retractions are remembered longer than the number.',
      '',
      '## three rules i keep coming back to',
      '',
      '- **quote the scope, not the hour.** hours are a measure of cost; scope is a measure of value. clients who ask for hours are looking for someone to manage; clients who ask for scope are looking for someone to trust.',
      '- **never discount without removing something.** if the number moves, the work must move with it. otherwise you teach the client that your quote was a first draft.',
      '- **write the number down before the meeting.** say it flatly, without a ladder of justifications. the number is the work. #rule',
      '',
      '> "cheap work finds you again later." — margaret, 2019',
      '',
      'there is a kind of dignity in a plain number, stated once, held through the meeting. it is not bravado and it is not stubbornness. it is the simplest form of respect for the thing you are about to build.',
      '',
      'the rest is follow-through.',
    ].join('\n'),
  },
  {
    id: 'n-hl7',
    pinned: true,
    tags: ['project/atlas', 'hl7', 'fhir'],
    body: [
      '# atlas — hl7 → fhir migration plan',
      '',
      'meeting with j. and the platform team on tuesday. they want a **timeline, not a proposal**. the ask is honest: eighteen months of pilot data, one claims backlog, and a compliance review that starts in may. we will not rebuild the intake layer; we will wrap it.',
      '',
      '## phase 01 — discovery',
      '',
      '- [x] shadow the intake desk for one shift (thursday, 7am)',
      '- [x] pull a week of `ADT^A01` feeds, anonymise',
      '- [ ] map `PID-3` assigning authorities → `Patient.identifier.system`',
      '- [ ] confirm sending-facility list with compliance',
      '- [ ] document the three known edge cases in the `MSH-4` field',
      '',
      '## phase 02 — build',
      '',
      '- [ ] mirth channel, staging only',
      '- [ ] golden-file tests, one per message type',
      '- [ ] `fhir_ig_validator` wired into CI on every PR',
      '- [ ] shadow-write to the FHIR store for two weeks before cutover',
      '',
      '## phase 03 — ship',
      '',
      '- [ ] dual-write window — minimum four weeks',
      '- [ ] reconciliation report, daily, emailed to j.',
      '- [ ] rollback playbook reviewed by _both_ ops leads',
      '',
      '## risks worth naming',
      '',
      '1. the vendor\'s `ORM^O01` dialect differs from the spec in three places; we own the translation.',
      '2. compliance has not signed off on the staging environment; block on this before week four.',
      '3. the audit log format is still under debate. default to `ndjson` and move on.',
      '',
      '> next review: fri 09:00, room 2b.',
      '',
      'estimate: **twelve weeks** from signed sow. buffer of two. after that we\'re borrowing time from ourselves. #project/atlas',
    ].join('\n'),
  },
  {
    id: 'n-tues',
    pinned: false,
    tags: ['meeting', 'project/meridian'],
    body: [
      '# tues standup — meridian',
      '',
      'present: a., k., p., me. p. out thursday, covered by a.',
      '',
      '## what moved',
      '',
      '- k. finished the claims parser; moving to reconciliation. handed off the fixtures cleanly, no tribal knowledge left on desktops.',
      '- a. blocked on SFTP creds from the client — escalating to j. this is the third week; we should set a hard deadline.',
      '- p. will draft the rollback doc before eod. short version, printed and signed, not a wiki page.',
      '',
      '## decisions',
      '',
      '1. freeze scope on the reconciliation view until the 30th. anything proposed after today goes to v2.',
      '2. audit log goes to s3, not the db. cheaper, append-only, and compliance already knows the bucket. #decision',
      '3. postpone the `export` feature to v2 — no user has asked for it and two have asked for import.',
      '',
      '## open threads',
      '',
      '- k. wants a pairing hour on the reconciliation query plan. wednesday after lunch.',
      '- the flaky test on `parse_remit_v3` is back. one of us owes it a proper afternoon.',
      '',
      '> next standup: thursday, 9.30. p. out, a. runs it.',
    ].join('\n'),
  },
  {
    id: 'n-reading',
    pinned: false,
    tags: ['reading', 'research'],
    body: [
      '# reading list — q2',
      '',
      'short list. anything longer i will not finish.',
      '',
      '- [ ] _the timeless way of building_ — alexander. bought in march, still on the pile. read slow, one pattern a night.',
      '- [x] _seeing like a state_ — scott. the best thing i read this year. legibility is not a feature; it is a tax.',
      '- [ ] _high output management_ — grove. reread. mark up the chapter on meetings.',
      '- [ ] papers on `CRDT` merge semantics #research — specifically the yjs work and automerge\'s 2023 retrospective.',
      '- [ ] _the design of everyday things_ — norman. skim only; i have read it twice.',
      '- [x] _a pattern language_ — alexander et al. reread pattern 159.',
      '',
      '## how i am reading',
      '',
      '- morning, twenty minutes, no phone on the desk.',
      '- margin notes in pencil. pen feels too final.',
      '- one sentence into the note app at the end of each session — the one sentence i would tell a friend.',
      '',
      'if a book does not change how i work by chapter three, i stop. there is no prize for finishing a book that does not owe you anything.',
    ].join('\n'),
  },
  {
    id: 'n-grocery',
    pinned: false,
    tags: ['todo'],
    body: [
      '# saturday',
      '',
      '- [ ] coffee — the ethiopian, not the blend',
      '- [ ] butter, unsalted',
      '- [x] bread, sourdough from the corner',
      '- [ ] lemons (3) and one lime, if they have them',
      '- [ ] tomatoes — on the vine, still warm if possible',
      '- [ ] call mum',
      '- [ ] drop the jacket at the tailor',
      '',
      'library closes at 5. if i am late it will be another week.',
    ].join('\n'),
  },
  {
    id: 'n-glyph',
    pinned: false,
    tags: ['writing', 'fragment'],
    body: [
      '# a fragment, for later',
      '',
      'a glyph is a small contract between a reader and a writer. it says: _i will give you this shape, and you will give me that sound_. the contract is invisible when it works and terrible when it does not.',
      '',
      'when the contract is good, the reading is invisible. when it is bad, the eye trips on every other word. a good face is one you never notice; a bad face is one you cannot stop noticing.',
      '',
      '## on kerning',
      '',
      'kerning is the apology a typographer makes for the alphabet. the letters were never going to fit. someone had to close the gaps.',
      '',
      '> design is just the contract, written very slowly.',
      '',
      'save this. use it somewhere — maybe the about page. maybe nowhere.',
    ].join('\n'),
  },
  {
    id: 'n-audit',
    pinned: false,
    tags: ['project/atlas', 'compliance'],
    body: [
      '# soc-2 audit — prep notes',
      '',
      'auditor arrives **12 may**. three things they will ask for, and we are short on one.',
      '',
      '1. access-review evidence, last two quarters. we have it, but it lives in three tools. consolidate by friday.',
      '2. incident postmortems — at least one with a blameless tone. we are short one.',
      '3. vendor list with data-processing addendums signed within the last year. missing two; chasing.',
      '',
      '## the missing postmortem',
      '',
      'write one from the **feb 14 page-out**. the facts: the on-call pager fired at 03:12, resolved at 04:48, no customer data touched. the lesson: our alert thresholds did not match reality after the march deploy.',
      '',
      '- [ ] draft by monday. one page.',
      '- [ ] circulate to k. and p. for tone',
      '- [ ] file under `/incidents/2026-02-14.md` #todo',
      '',
      '---',
      '',
      '> "if the auditor finds it, you will find it twice." — ops handbook, 2021',
    ].join('\n'),
  },
  {
    id: 'n-meridian-kickoff',
    pinned: false,
    tags: ['project/meridian', 'meeting'],
    body: [
      '# meridian — kickoff prep',
      '',
      'first meeting with the whole team on monday, 10am. sixty minutes. do not let it run over.',
      '',
      '## the agenda i will actually use',
      '',
      '1. fifteen minutes: what the product does, in their words, not ours.',
      '2. fifteen minutes: the three failure modes of the previous build.',
      '3. twenty minutes: draw the new data flow on the board, together.',
      '4. ten minutes: decide the first two weeks of work.',
      '',
      'no slides. if i cannot draw it in a marker, i do not understand it yet.',
      '',
      '## questions to hold in reserve',
      '',
      '- who owns the claims schema after go-live?',
      '- what does failure look like in month six?',
      '- what is the _one_ report the head of finance opens every monday?',
      '',
      '> short meetings, sharp notes.',
    ].join('\n'),
  },
  {
    id: 'n-interview',
    pinned: false,
    tags: ['hiring'],
    body: [
      '# interview — r. (staff eng, platform)',
      '',
      'strong. the kind of strong that is hard to see in a single hour.',
      '',
      '## signal',
      '',
      '- read the prompt twice before typing. not a nervous habit — a working habit.',
      '- talked about a rollback like someone who has written one in anger.',
      '- described a failed migration _without_ blaming the previous team. rare.',
      '',
      '## noise',
      '',
      '- overindexed on `kubernetes` in the architecture question. we are not that shop.',
      '- the writing sample was tidy but thin. ask for a longer one.',
      '',
      '## recommendation',
      '',
      '- [x] progress to on-site',
      '- [ ] pair on a real bug, not a contrived exercise',
      '- [ ] schedule the architecture deep-dive with j.',
      '',
      '> "hire for the second year, not the first three months." #rule',
    ].join('\n'),
  },
  {
    id: 'n-studio',
    pinned: false,
    tags: ['writing', 'essay/studio'],
    body: [
      '# notes toward a studio of three',
      '',
      'three is the number. two is a partnership, which is a different thing. four is a company, which is a different thing again. three is a studio — enough cover for illness, enough room for disagreement, too small to hide in.',
      '',
      '## what a studio of three owes itself',
      '',
      '- a weekly hour where nobody talks about work.',
      '- a shared document that is _only_ updated when something changes.',
      '- a rule about who decides when two agree and one does not.',
      '',
      '## what it owes its clients',
      '',
      'an invoice on the day. a draft on the day. a name at the bottom of every email — not the company, the person.',
      '',
      '> small, slow, specific.',
    ].join('\n'),
  },
  {
    id: 'n-errata',
    pinned: false,
    tags: ['writing', 'errata'],
    body: [
      '# errata — things i got wrong this year',
      '',
      'a running list. the point is not penance; the point is to notice the pattern.',
      '',
      '1. **quoted a fixed fee on a scope that was not fixed.** cost: four weeks. lesson: refuse the number until the scope is on paper.',
      '2. **hired for speed instead of judgment.** cost: two months of rework. lesson: the fast person who ships the wrong thing costs more than the slow person who ships the right thing.',
      '3. **skipped a postmortem because "everyone knew what happened."** cost: the next outage, which was the same outage. lesson: the postmortem is for the _next_ team, not this one.',
      '',
      '---',
      '',
      '> the only useful mistake is the one you write down.',
    ].join('\n'),
  },
  {
    id: 'n-commute',
    pinned: false,
    tags: ['fragment'],
    body: [
      '# seen on the commute',
      '',
      'a woman on the 38 bus reading a paperback with the cover torn off. she had wrapped it in brown paper and written the title on the paper in pencil. the title was in a language i did not recognise. she was most of the way through.',
      '',
      'i think about this more than i should.',
    ].join('\n'),
  },
];

// Stagger timestamps so the default library reads like a real week of notes.
const OFFSETS = [
  0,
  3 * HOUR,
  1 * DAY,
  3 * DAY,
  4 * DAY,
  5 * DAY,
  6 * DAY,
  7 * DAY,
  7 * DAY + 4 * HOUR,
  8 * DAY,
  9 * DAY,
  10 * DAY,
];

export const SEED_NOTES = SOURCES.map((n, i) => ({
  id: n.id,
  body: n.body,
  pinned: n.pinned,
  tags: n.tags,
  created: NOW - 30 * DAY - i * DAY,
  updated: NOW - (OFFSETS[i] ?? i * DAY),
}));
